name: "Docker Context"
description: "Set up a Remote Docker Context over SSH using Password or Keyfile Authentication"
author: "Shane"
branding:
  icon: "sliders"
  color: "blue"

inputs:
  host:
    description: "Docker Host"
    required: true
  user:
    description: "Docker User"
    required: true
  port:
    description: "Docker Port"
    default: "22"
  pass:
    description: "SSH Password"
  ssh_key:
    description: "SSH Key File"
  registry_user:
    description: "Registry Auth Username"
  registry_pass:
    description: "Registry Auth Password"
  registry_host:
    description: "Registry Auth Hostname"
  token:
    description: "GitHub Access Token PAT"
    default: ${{ github.token }}

runs:
  using: "node24"
  main: "dist/index.js"
  post: "dist/index.js"
