name: "Docker Context"
description: "Set up a Remote Docker Context over SSH using Password or Keyfile Authentication"
author: "Shane"
branding:
  icon: "sliders"
  color: "blue"

inputs:
  host:
    description: "Docker Host"
    required: true
  user:
    description: "Docker User"
    required: true
  port:
    description: "Docker Port"
    required: true
    default: "22"
  pass:
    description: "SSH Password"
  ssh_key:
    description: "SSH Key File"
  registry_user:
    description: "Registry Auth Username"
  registry_pass:
    description: "Registry Auth Password"
  registry_host:
    description: "Registry Auth Hostname"

runs:
  using: "composite"
  steps:
    - name: "Running step: src/ssh.sh"
      id: ssh
      shell: bash
      env:
        INPUT_HOST: ${{ inputs.host }}
        INPUT_USER: ${{ inputs.user }}
        INPUT_PORT: ${{ inputs.port }}
        INPUT_PASS: ${{ inputs.pass }}
        INPUT_INPUT_SSH_KEY: ${{ inputs.ssh_key }}
      run: source ${{ github.action_path }}/src/ssh.sh

    - name: "Running step: src/context.sh"
      id: context
      shell: bash
      env:
        INPUT_HOST: ${{ inputs.host }}
        INPUT_USER: ${{ inputs.user }}
        INPUT_PORT: ${{ inputs.port }}
      run: source ${{ github.action_path }}/src/context.sh
